[package]
name = "terminfo-lean"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "MIT OR Apache-2.0"
authors = ["Pavel Roskin", "The Rust Project Developers"]

[dependencies]
num_enum = "0.7.5"
thiserror = "2.0.17"

[dev-dependencies]
temp-env = "0.3.6"
tempdir = "0.3.7"
